### PR TITLE
Revert "Add map contest winner trophy"

### PR DESCRIPTION
**Pull request by Matic0B**
Reverts StratusNetwork/Data#8

They were already added

### CODE REVIEW

**Comment by mitchiiii** [comment]
I think it would be better to have a generic one rather than specifics. Map contests aren't held as highly as tournaments are, so I don't see the need for individual trophies. It's also easier and less of a hassle for the future.

**Comment by Matic0B** [comment]
I think we should have individual trophies just to show which contest a person won. No reason not to do that even if they're not held as highly as tournaments.

**Comment by Szboy** [comment]
I'm inclined to agree with mitchiiii, it would get cluttered fast.

**Comment by Matic0B** [comment]
We should reward the map making community as much as we can because they are going to be keeping fresh content flowing in the terms of maps. I think having individual trophies is a very small thing but it makes the trophies more personal. You didn't just win some map contest, you won that specific map contest.

I'd love to reward map makers and tournament teams more in the future with even having participation awards (automated) but this is something that can be done now and it doesn't take much effort so it should be done.

I believe tournaments and map contests are both extremely important for the community and should both have individual trophies for their events.

**Pull request merged**
